spring:
  application:
    name: url-shortener

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Changed from 'update' to 'validate' for Flyway
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: false  # Let Flyway handle schema creation

  # Flyway Configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true  # Prevent accidental data loss
    baseline-version: 0
    baseline-description: Initial baseline

  # SQL Initialization (disabled in favor of Flyway)
  sql:
    init:
      mode: never  # Disabled - using Flyway instead

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Application Configuration
app:
  base-url: http://localhost:8080/api/v1

# Logging Configuration
logging:
  level:
    com.example.urlshortener: DEBUG
    org.hibernate.SQL: DEBUG
    org.flywaydb: INFO

# Management Endpoints (for monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,flyway
  endpoint:
    health:
      show-details: when_authorized