spring:
  # PostgreSQL Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  # JPA Configuration for PostgreSQL
  jpa:
    hibernate:
      ddl-auto: validate  # Use Flyway for schema management
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Configuration for PostgreSQL
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    baseline-version: 0
    baseline-description: Initial baseline

  # Disable H2 Console
  h2:
    console:
      enabled: false