spring:
  application:
    name: url-shortener

  # Database Configuration - H2 In-Memory Database
  datasource:
    url: jdbc:h2:mem:urlshortener;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop  # Let Hibernate create schema since we're using H2
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: false

  # H2 Console Configuration (for debugging)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  # Flyway Configuration - Disabled for H2 development
  flyway:
    enabled: false  # Disable Flyway, let Hibernate handle schema creation

  # SQL Initialization
  sql:
    init:
      mode: never

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Application Configuration
app:
  base-url: http://localhost:8080/api/v1

# Logging Configuration
logging:
  level:
    com.example.urlshortener: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.web: DEBUG

# Management Endpoints (for monitoring)
management:
  endpoints:
    web:
      exposure:
        include: health,info,h2
  endpoint:
    health:
      show-details: always