spring:
  application:
    name: url-shortener

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/urlshortener
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    defer-datasource-initialization: true

  # SQL Initialization
  sql:
    init:
      mode: always
      platform: postgresql

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Logging Configuration
logging:
  level:
    com.example.urlshortener: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE